# Generated by Django 4.2.19 on 2025-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='case_number',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='hospital_case_number',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_number',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_case_number',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
