# Generated by Django 4.2.19 on 2025-06-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
