# Generated by Django 4.2.19 on 2025-06-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historicalpatient_archived_patient_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpatient',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient'},
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
