# Generated by Django 4.2.19 on 2025-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historicalpatient_case_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='entry_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
