# Generated by Django 4.2.19 on 2025-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_services_billing_patient_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientservice",
            name="cost_at_time",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
