# Generated by Django 4.2.19 on 2025-06-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_historicalpatient_entry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpatient',
            old_name='admission_datetime',
            new_name='admission_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='admission_datetime',
            new_name='admission_date',
        ),
    ]
