# Generated by Django 4.2.19 on 2025-06-29 01:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_backuphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='case_number',
            field=models.CharField(db_index=True, default=api.models.generate_case_number, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_number',
            field=models.CharField(db_index=True, default=api.models.generate_case_number, max_length=255, unique=True),
        ),
    ]
