# Generated by Django 4.2.19 on 2025-06-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedassignment',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.billing'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='bed_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bedassignment'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='service_availed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patientservice'),
        ),
    ]
