# Generated by Django 4.2.19 on 2025-07-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_department_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Assigned based on attending doctor's specialization", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.department'),
        ),
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Assigned based on attending doctor's specialization", null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department'),
        ),
    ]
