# Generated by Django 4.2.19 on 2025-06-18 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_date_joined_user_email_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='dose_frequency',
            field=models.CharField(blank=True, help_text="e.g. 'Once daily', '2x per day'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='focus_problem',
            field=models.TextField(blank=True, help_text='Primary problem or focus of this note', null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='medication',
            field=models.CharField(blank=True, help_text='Medication name (for Medication notes)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='note_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date/time for this note (can represent shift)', null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='orders',
            field=models.TextField(blank=True, help_text='Any new orders (labs, imaging, meds, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='Progress since last note', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='author',
            field=models.ForeignKey(help_text='Who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='content',
            field=models.TextField(blank=True, help_text='General narrative (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='note_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor Note'), ('Nurse', 'Nurse Note'), ('General', 'General Note'), ('Medication', 'Medication Note')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
