# Generated by Django 4.2.19 on 2025-06-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_clinicalnote_dose_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='hmo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='hospital_case_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hmo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_case_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
