# Generated by Django 4.2.19 on 2025-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_historicalpatient_hmo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='case_number_patient',
            field=models.TextField(blank=True, help_text='General narrative (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_number',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
