# Generated by Django 4.2.19 on 2025-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_icdtodepartmentmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Outpatient', 'Outpatient'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Outpatient', 'Outpatient'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
