# Generated by Django 4.2.19 on 2025-07-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_historicalpatient_status_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Outpatient', 'Outpatient'), ('Pending', 'Pending'), ('Ready_for_Coding', 'Ready_for_Coding')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='type_of_admission',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Elective', 'Elective'), ('New', 'New'), ('Old/Former', 'Old/Former'), ('OPD', 'OPD')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Outpatient', 'Outpatient'), ('Pending', 'Pending'), ('Ready_for_Coding', 'Ready_for_Coding')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_admission',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Elective', 'Elective'), ('New', 'New'), ('Old/Former', 'Old/Former'), ('OPD', 'OPD')], default='Pending', max_length=20, null=True),
        ),
    ]
