# Generated by Django 4.2.19 on 2025-07-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_historicalpatient_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='type_of_admission',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Elective', 'Elective'), ('New', 'New'), ('Old/Former', 'Old/Former'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_admission',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Elective', 'Elective'), ('New', 'New'), ('Old/Former', 'Old/Former'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
    ]
