# Generated by Django 4.2.19 on 2025-07-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_historicalpatient_type_of_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='intended_admission_type',
            field=models.CharField(blank=True, choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), (None, 'Not Set')], default=None, help_text='Set by clinical staff to indicate if patient will be inpatient or outpatient', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='intended_admission_type',
            field=models.CharField(blank=True, choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), (None, 'Not Set')], default=None, help_text='Set by clinical staff to indicate if patient will be inpatient or outpatient', max_length=20, null=True),
        ),
    ]
