# Generated by Django 4.2.19 on 2025-07-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_historicalpatient_intended_admission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='case_number',
            field=models.CharField(blank=True, help_text='Historical patient case number (nullable until linked)', max_length=50, null=True),
        ),
    ]
