# Generated by Django 4.2.19 on 2025-07-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_billing_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Teller', 'Teller'), ('Receptionist', 'Receptionist'), ('Patient', 'Patient')], max_length=20),
        ),
    ]
