# Generated by Django 4.2.19 on 2025-06-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('HAMA', 'Left Against Medical Advice'), ('Absconded', 'Absconded')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='father_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='father_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='membership',
            field=models.CharField(blank=True, choices=[('SSS', 'SSS'), ('GSIS', 'GSIS'), ('Both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='mother_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='result',
            field=models.CharField(blank=True, choices=[('Recovered', 'Recovered'), ('Died', 'Died'), ('48h_minus', '48 hours (-)'), ('48h_plus', '48 hours (+)'), ('Improved', 'Improved'), ('Unimproved', 'Unimproved'), ('Autopsy', 'Autopsy'), ('No_autopsy', 'No Autopsy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='spouse_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='spouse_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('HAMA', 'Left Against Medical Advice'), ('Absconded', 'Absconded')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='membership',
            field=models.CharField(blank=True, choices=[('SSS', 'SSS'), ('GSIS', 'GSIS'), ('Both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='result',
            field=models.CharField(blank=True, choices=[('Recovered', 'Recovered'), ('Died', 'Died'), ('48h_minus', '48 hours (-)'), ('48h_plus', '48 hours (+)'), ('Improved', 'Improved'), ('Unimproved', 'Unimproved'), ('Autopsy', 'Autopsy'), ('No_autopsy', 'No Autopsy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
