# Generated by Django 4.2.19 on 2025-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_historicalpatient_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='bed_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='ward_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bed_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
