# Generated by Django 4.2.19 on 2025-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_patient_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
