# Generated by Django 4.2.19 on 2025-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_historicalpatient_age_historicalpatient_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='type_of_admission',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Elective', 'Elective')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_of_admission',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Elective', 'Elective')], max_length=20, null=True),
        ),
    ]
