# Generated by Django 4.2.19 on 2025-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_historicalpatient_email_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='final_admission_type',
            field=models.CharField(blank=True, choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), ('Undecided', 'Undecided'), (None, 'Not Set')], default=None, help_text="Doctor's final decision on admission type after clinical review", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='final_admission_type',
            field=models.CharField(blank=True, choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), ('Undecided', 'Undecided'), (None, 'Not Set')], default=None, help_text="Doctor's final decision on admission type after clinical review", max_length=20, null=True),
        ),
    ]
