# Generated by Django 4.2.19 on 2025-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_historicalpatient_other_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('HAMA', 'HAMA'), ('Absconded', 'Absconded')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('HAMA', 'HAMA'), ('Absconded', 'Absconded')], max_length=20, null=True),
        ),
    ]
