# Generated by Django 4.2.19 on 2025-07-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_historicalpatient_final_admission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to patient record if this user is a patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='api.patient'),
        ),
    ]
