# Generated by Django 4.2.19 on 2025-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_historicalpatient_disposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
