# Generated by Django 4.2.19 on 2025-06-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_historicalpatient_age_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='total_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
