# Generated by Django 4.2.19 on 2025-06-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_historicalpatient_total_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='diagnosed_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnosed_by',
        ),
    ]
