# Generated by Django 4.2.19 on 2025-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_historicalpatient_type_of_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old/Former', 'Old/Former'), ('OPD', 'OPD'), ('Follow-Up', 'Follow-Up')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old/Former', 'Old/Former'), ('OPD', 'OPD'), ('Follow-Up', 'Follow-Up')], max_length=20, null=True),
        ),
    ]
