# Generated by Django 4.2.19 on 2025-06-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_historicalpatient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
    ]
